name: TF create

on:
  push:

jobs:
  TF-create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set AWS Keys
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}

      - name: TF-INIT-PLAN-APPLY
        needs: set-aws-keys
        run: |
          cd Terraform
          terraform init
          terraform plan 
          terraform apply -auto-approve 
          #terraform destroy -auto-approve

      - name: UnSet AWS Keys
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY