name: TF create/destroy

on:
  workflow_dispatch:

jobs:
  TF-create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: TF-INIT-PLAN-APPLY
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}

          chmod u+x Scripts/tf-apply.sh
          sh Scripts/tf-apply.sh

          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
