name: TF create

on:
  push:
    branches:
      - main

jobs:
  TF-create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Setting AWS credentials..."
          echo $AWS_ACCESS_KEY_ID > ~/.aws/credentials
          echo $AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
          chmod 600 ~/.aws/credentials

                # Run your deployment commands here
                # For example:
                # aws s3 sync ./s3-bucket s3://my-bucket


      - name: TF-step-1-2-3
              run: |
                pwd && ls
                cd Terraform
                pwd
                terraform init
                terraform plan -var "access_key=${{ secrets.AWS_ACCESS_KEY }}" -var "secret_key=${{ secrets.AWS_SECRET_KEY }}"
                terraform apply -auto-approve -var "access_key=${{ secrets.AWS_ACCESS_KEY }}" -var "secret_key=${{ secrets.AWS_SECRET_KEY }}"
                #terraform destroy -auto-approve -var "access_key=${{ secrets.AWS_ACCESS_KEY }}" -var "secret_key=${{ secrets.AWS_SECRET_KEY }}"

      - name: Unset AWS credentials
        run: |
          echo "Unsetting AWS credentials..."
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          rm -f ~/.aws/credentials